minecraft_version=1.19.2
forge_version=43.5.0
forge_version_range=[43.5.0,44)
loader_version_range=[43,)
minecraft_version_range=[1.19.2,1.20)
buildcraft_version=8.0.14+1.19.2+forge
buildcraft_local_jar=libs/BuildCraft-Community-Edition-8.0.14+1.19.2+forge.jar
buildcraft_version_range=[8.0.14,)
java_version=17
forge_reobf=true
