minecraft_version=1.21.1
neo_version=21.1.244
neo_version_range=[21.1.244,)
loader_version_range=[1,)
minecraft_version_range=[1.21.1,1.21.2)
buildcraft_version=8.0.14+1.21.1+neoforge
buildcraft_local_jar=libs/BuildCraft-Community-Edition-8.0.14+1.21.1+neoforge.jar
buildcraft_version_range=[8.0.14,)
java_version=21
